version: '3.8'

services:
  application:
    restart: always
    build: .
    environment:
      TOKEN: ${TOKEN}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_HOST: ${SQL_HOST}
    env_file:
      - ./.env
    depends_on:
        - db
  db:
    image: postgres:12.0-alpine
    container_name: db_rabotov
    restart: always
    environment:
      - POSTGRES_USER=bot_admin
      - POSTGRES_PASSWORD=bot_admin
      - POSTGRES_DB=rabotov_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: